### ISSUE TITLE
CP crash on launch

### ISSUE THREAD

**Issue by foxsr** [fabrylab/clickpoints#12]
Regression from version 1.9.5

potentially related with file loader changes 

Starting CP from cmd line results in repeated error messages:

> 
> C:\Users\Fox>clickpoints
> args ['C:\\ProgramData\\Anaconda3\\Scripts\\clickpoints']
> ClickPoints 1.9.6
> Using Python 3.7.4 final 64bit
> Using PyQt5 5.14.1
> LoadConfig ['C:\\ProgramData\\Anaconda3\\Scripts\\clickpoints']  False
> use custom openslide variant with tifffile
> Searching ImageIO Plugins ...
> ffmpeg found from imageio
> Loading url
> Traceback (most recent call last):
>   File "c:\software\clickpoints\clickpoints\modules\Timeline.py", line 1055, in ImagesAddedMain
>     self.frameSlider.setRange(0, self.get_frame_count() - 1)
>   File "c:\software\clickpoints\clickpoints\modules\Timeline.py", line 1043, in get_frame_count
>     return self.data_file.get_image_count()
> AttributeError: 'NoneType' object has no attribute 'get_image_count'
> LoadingFinishedEvent <clickpoints.modules.FolderEditor.FolderEditor object at 0x000002A01BF39D38>
> Traceback (most recent call last):
>   File "c:\software\clickpoints\clickpoints\Core.py", line 201, in <lambda>
>     self.start_timer = QtCore.QTimer.singleShot(1, lambda: self.loadUrl(config.srcpath))
>   File "c:\software\clickpoints\clickpoints\Core.py", line 238, in loadUrl
>     self.data_file = loadUrl(url, self.data_file, window=self, use_natsort=use_natsort, reset=reset, loop=self.app.loop, callback_finished=loadingFinished)
>   File "c:\software\clickpoints\clickpoints\includes\loader.py", line 152, in loadUrl
>     callback_finished(data_file)
>   File "c:\software\clickpoints\clickpoints\Core.py", line 232, in loadingFinished
>     BroadCastEvent(self.modules, "LoadingFinishedEvent")
>   File "c:\software\clickpoints\clickpoints\includes\Tools.py", line 80, in BroadCastEvent
>     getattr(module, function)(*args, **kwargs)
>   File "c:\software\clickpoints\clickpoints\modules\Timeline.py", line 1077, in LoadingFinishedEvent
>     if self.data_file.getOption("datetimeline_show"):
> AttributeError: 'NoneType' object has no attribute 'getOption'
> Traceback (most recent call last):
>   File "c:\software\clickpoints\clickpoints\Core.py", line 256, in LoadTimer
>     if self.data_file.image is None and self.data_file.get_image_count() and self.first_frame is not None:
> AttributeError: 'NoneType' object has no attribute 'image'
> Task exception was never retrieved
> future: <Task finished coro=<ClickPointsWindow.load_frame() done, defined at c:\software\clickpoints\clickpoints\Core.py:313> exception=AttributeError("'NoneType' object has no attribute 'get_image_count'")>
> Traceback (most recent call last):
>   File "c:\software\clickpoints\clickpoints\Core.py", line 315, in load_frame
>     if self.data_file.get_image_count() == 0:
> AttributeError: 'NoneType' object has no attribute 'get_image_count'
> Traceback (most recent call last):
>   File "c:\software\clickpoints\clickpoints\Core.py", line 256, in LoadTimer
>     if self.data_file.image is None and self.data_file.get_image_count() and self.first_frame is not None:
> AttributeError: 'NoneType' object has no attribute 'image'
> Traceback (most recent call last):
>   File "c:\software\clickpoints\clickpoints\Core.py", line 256, in LoadTimer
>     if self.data_file.image is None and self.data_file.get_image_count() and self.first_frame is not None:
> AttributeError: 'NoneType' object has no attribute 'image'`

the last error is repeated endlessly

same error for fresh install

**Comment by foxsr** [comment]
breaks with commit a3b0cff13c0834d2183c08b930c340122dc0781f

**Comment by foxsr** [comment]
thx
